version: '3'

services:
  wordpress:
    container_name: wpdiscussionboard
    restart: always
    depends_on:
      - wpdiscussionboard_db
    links:
      - wpdiscussionboard_db:mysql
    image: andreccosta/wordpress-xdebug
    ports:
      - "8092:80"
    env_file:
      - .env
    volumes:
      - ./wp:/var/www/html/
      - .:/var/www/html/wp-content/plugins/wp-discussion-board
      - ./vendor/wp-phpunit/wp-phpunit:/var/www/html/tests/phpunit
      - ./public/wp-tests-config.php:/var/www/html/wp-tests-config.php
    networks:
      - local
    environment:
      WP_TESTS_DIR: /var/www/html/tests/phpunit
      WP_PHPUNIT__TESTS_CONFIG: /var/www/html/wp-tests-config.php
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: start_with_request=yes client_host=host.docker.internal client_port=9000 remote_host=host.docker.internal

  wpdiscussionboard_db:
    container_name: wpdiscussionboard_mysql
    image: mysql:5.7
    ports:
      - "3332:3306"
    env_file:
      - .env
    volumes:
      - "./docker/data/db:/var/lib/mysql"
    networks:
      - local

  wordpress_phpunit:
    container_name: wpdiscussionboard_wordpress_phpunit
    image: "chriszarate/wordpress-phpunit"
    volumes:
      - ".:/app"
    environment:
      WP_TESTS_DIR: /app/vendor/wp-phpunit/wp-phpunit
      WP_PHPUNIT__TESTS_CONFIG: /app/tests/wp-tests-config.php
    networks:
      - local

  mysql_phpunit:
    container_name: wpdiscussionboard_mysql_phpunit
    image: mysql:5.7
    env_file:
      - .env.tests
    networks:
      - local

networks:
  local:
    external: true
