name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New version
    runs-on: ubuntu-latest
    environment: WPDiscussionBoard
    steps:
      - uses: actions/checkout@master
      - name: Deploy Plugin
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_WPORG_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_WPORG_USERNAME }}
