name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Plugin
        run: |
          composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: Deploy Plugin
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_WPORG_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_WPORG_USERNAME }}
