name: Sync assets with wordpress.org
on:
  push:
    branches:
      - master
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'
jobs:
  run:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(assets)')"
    name: Push assets to wporg
    steps:
      - uses: actions/checkout@master
      - name: Update assets on WordPress.org
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_WPORG_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_WPORG_USERNAME }}